config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable
	has_many :products, dependent: :destroy

	#return public products
	def public_products
		return Product.where(is_private: false)
	end

	#return current user products
	def my_products
		return self.products
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController	
	def index
		@products = current_user.public_products
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = current_user.my_products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
      if @product.save
        redirect_to products_path
      else
        redirect_to new_product_path
      end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:prd_name, :user_id, :is_private, :image, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<section class="gernal upcoming_tabl">
  <div class="container">
    <h2>Public Products</h2>   
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4">
          <div class="thumbnail">
            <a href="#">
              <img src="<%=product.image.url%>" alt="Lights" style="width:100%">
              <div class="caption">
                <p><%=truncate(product.description,length: 100 ) %></p>
              </div>
            </a>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<header class="header">
   <div class="container-fluid">
      <div class="row">
         <aside class="col-sm-1 col-xs-9 log_haeder haede_sctn">
         </aside>
         <aside class="col-sm-11 col-xs-3">
            <nav class="navbar navbar-default custom_navigation new_nav profile">
               <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>          
               </div>
               <div aria-expanded="false" id="navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav searc_he pull-left">
                     <% if params[:controller] == "home" %>
                        <li class="active">
                     <%else%>
                        <li>
                     <%end%>
                           <%= link_to "Public Products" %>
                        </li> 
                     <% if request.fullpath.split(/[?^\/]/).include?("products") && params[:action] == "index"  %>
                        <li class="active">
                     <% else %>
                        <li>
                     <% end %>
                           <%= link_to "My Products", products_path %>
                     </li>
                     <% if request.fullpath.split(/[?^\/]/).include?("new") && params[:action] == "new"  %>
                        <li class="active">
                     <% else %>
                        <li>
                     <% end %>
                           <%= link_to "Create Product", new_product_path %>
                     </li>               
                  </ul>
                  <%= link_to :logout, destroy_user_session_path, :method => :delete, class: 'sign_out' %>
               </div>
            </nav>
         </aside>
      </div>
   </div>
</header>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? %>
      <%= render 'layouts/header' %>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<section class="page-login height100">  
  <aside class="col-sm-12">
    <%=  form_with(model: product, local: true, html: {class: 'welcome'}) do |form| %>
      <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
      <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
      <%= content_tag(:div, flash[:alert], :id => "flash_alert",:class=>"alert-danger") if flash[:alert] %>
      <div class="welcome_top">
        <h2>Create Your Product</h2>
     </div> 
      <%= form.hidden_field :user_id , value: current_user.id%>
      <div class="forn_field">
        <div class="form-group form_g">
          <%= form.label :prd_name, class: "cus_label" %>
          <%= form.text_field :prd_name , class: "form-control"%>
        </div>
        <div class="form-group form_g">
          <%= form.label :description, class: "cus_label" %>
          <%= form.text_area :description , class: "form-control"%>
        </div>
        <div class="form-group form_g">
          <%= form.label :image, class: "cus_label" %>
          <%= form.file_field(:image, accept: 'image/png,image/gif,image/jpeg', class: 'form-control')%>
        </div>
        <div class="form-group form_g">
          <%= form.label :is_private, class: "cus_label" %>
          <%= form.check_box :is_private%>
        </div>
      </div> 
      <div class="sign_bt">
        <%= form.submit "Submit", :class => 'btn2'%>
      </div>
    <% end %>
  </aside>
</section>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<section class="gernal upcoming_tabl">
  <div class="container">
    <h2>Public Products</h2>   
    <div class="row">
      <% @products.each do |product| %>
        <div class="col-md-4">
          <div class="thumbnail">
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
              <img src="<%=product.image.url%>" alt="Lights" style="width:100%">
              <div class="caption">
                <p><%=truncate(product.description,length: 100 )%></p>
              </div>
            </a>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prd name:</strong>
  <%= @product.prd_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user %>
</p>

<p>
  <strong>Is private:</strong>
  <%= @product.is_private %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>